//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 10:12:49 上午 CST 
//


package com.ailk.check.xsd.smjkr;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ailk.random.xsd.smjkr package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ailk.random.xsd.smjkr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Smp }
     * 
     */
    public Smp createSmp() {
        return new Smp();
    }

    /**
     * Create an instance of {@link Smp.Data }
     * 
     */
    public Smp.Data createSmpData() {
        return new Smp.Data();
    }

    /**
     * Create an instance of {@link Smp.Data.Rcd }
     * 
     */
    public Smp.Data.Rcd createSmpDataRcd() {
        return new Smp.Data.Rcd();
    }

}
