package com.ailk.uap.makefile4new.sql;

import com.ailk.uap.makefile4new.constant.BusiCode;

/**
 * 对应规范V3.0
 * 章节10.2.18	金库分场景操作及授权统计日增量文件相关SQL定义
 *
 * @author  wangdz
 * @version 2.0
 */

public interface GoldSceneOperateDayAddFileSQL extends BusiCode{
	
  public static final String A4_GOLD_OPERATE_APP_PART1_SQL =
   "SELECT 'APP' RESTYPE,																																														"
  +"       CASE                                                                                                     "
  +"        TO_CHAR((TRUNC(SYSDATE) +                                                                               "
  +"                TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                        "
  +"                                        'yyyymmdd hh24:mi:ss'),                                                 "
  +"                                'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),       "
  +"                'hh24:mi') || '-' ||                                                                            "
  +"        TO_CHAR((TRUNC(SYSDATE) +                                                                               "
  +"                TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                        "
  +"                                        'yyyymmdd hh24:mi:ss'),                                                 "
  +"                                'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 ) * 30 / 60 / 24),   "
  +"                'hh24:mi')                                                                                      "
  +"         WHEN '00:00-00:30' THEN                                                                                "
  +"          '1'                                                                                                   "
  +"         WHEN '00:30-01:00' THEN                                                                                "
  +"          '2'                                                                                                   "
  +"         WHEN '01:00-01:30' THEN                                                                                "
  +"          '3'                                                                                                   "
  +"         WHEN '01:30-02:00' THEN                                                                                "
  +"          '4'                                                                                                   "
  +"         WHEN '02:00-02:30' THEN                                                                                "
  +"          '5'                                                                                                   "
  +"         WHEN '02:30-03:00' THEN                                                                                "
  +"          '6'                                                                                                   "
  +"         WHEN '03:00-03:30' THEN                                                                                "
  +"          '7'                                                                                                   "
  +"         WHEN '03:30-04:00' THEN                                                                                "
  +"          '8'                                                                                                   "
  +"         WHEN '04:00-04:30' THEN                                                                                "
  +"          '9'                                                                                                   "
  +"         WHEN '04:30-05:00' THEN                                                                                "
  +"          '10'                                                                                                  "
  +"         WHEN '05:00-05:30' THEN                                                                                "
  +"          '11'                                                                                                  "
  +"         WHEN '05:30-06:00' THEN                                                                                "
  +"          '12'                                                                                                  "
  +"         WHEN '06:00-06:30' THEN                                                                                "
  +"          '13'                                                                                                  "
  +"         WHEN '06:30-07:00' THEN                                                                                "
  +"          '14'                                                                                                  "
  +"         WHEN '07:00-07:30' THEN                                                                                "
  +"          '15'                                                                                                  "
  +"         WHEN '07:30-08:00' THEN                                                                                "
  +"          '16'                                                                                                  "
  +"         WHEN '08:00-08:30' THEN                                                                                "
  +"          '17'                                                                                                  "
  +"         WHEN '08:30-09:00' THEN                                                                                "
  +"          '18'                                                                                                  "
  +"         WHEN '09:00-09:30' THEN                                                                                "
  +"          '19'                                                                                                  "
  +"         WHEN '09:30-10:00' THEN                                                                                "
  +"          '20'                                                                                                  "
  +"         WHEN '10:00-10:30' THEN                                                                                "
  +"          '21'                                                                                                  "
  +"         WHEN '10:30-11:00' THEN                                                                                "
  +"          '22'                                                                                                  "
  +"         WHEN '11:00-11:30' THEN                                                                                "
  +"          '23'                                                                                                  "
  +"         WHEN '11:30-12:00' THEN                                                                                "
  +"          '24'                                                                                                  "
  +"         WHEN '12:00-12:30' THEN                                                                                "
  +"          '25'                                                                                                  "
  +"         WHEN '12:30-13:00' THEN                                                                                "
  +"          '26'                                                                                                  "
  +"         WHEN '13:00-13:30' THEN                                                                                "
  +"          '27'                                                                                                  "
  +"         WHEN '13:30-14:00' THEN                                                                                "
  +"          '28'                                                                                                  "
  +"         WHEN '14:00-14:30' THEN                                                                                "
  +"          '29'                                                                                                  "
  +"         WHEN '14:30-15:00' THEN                                                                                "
  +"          '30'                                                                                                  "
  +"         WHEN '15:00-15:30' THEN                                                                                "
  +"          '31'                                                                                                  "
  +"         WHEN '15:30-16:00' THEN                                                                                "
  +"          '32'                                                                                                  "
  +"         WHEN '16:00-16:30' THEN                                                                                "
  +"          '33'                                                                                                  "
  +"         WHEN '16:30-17:00' THEN                                                                                "
  +"          '34'                                                                                                  "
  +"         WHEN '17:00-17:30' THEN                                                                                "
  +"          '35'                                                                                                  "
  +"         WHEN '17:30-18:00' THEN                                                                                "
  +"          '36'                                                                                                  "
  +"         WHEN '18:00-18:30' THEN                                                                                "
  +"          '37'                                                                                                  "
  +"         WHEN '18:30-19:00' THEN                                                                                "
  +"          '38'                                                                                                  "
  +"         WHEN '19:00-19:30' THEN                                                                                "
  +"          '39'                                                                                                  "
  +"         WHEN '19:30-20:00' THEN                                                                                "
  +"          '40'                                                                                                  "
  +"         WHEN '20:00-20:30' THEN                                                                                "
  +"          '41'                                                                                                  "
  +"         WHEN '20:30-21:00' THEN                                                                                "
  +"          '42'                                                                                                  "
  +"         WHEN '21:00-21:30' THEN                                                                                "
  +"          '43'                                                                                                  "
  +"         WHEN '21:30-22:00' THEN                                                                                "
  +"          '44'                                                                                                  "
  +"         WHEN '22:00-22:30' THEN                                                                                "
  +"          '45'                                                                                                  "
  +"         WHEN '22:30-23:00' THEN                                                                                "
  +"          '46'                                                                                                  "
  +"         WHEN '23:00-23:30' THEN                                                                                "
  +"          '47'                                                                                                  "
  +"         WHEN '23:30-00:00' THEN                                                                                "
  +"          '48'                                                                                                  "
  +"         ELSE                                                                                                   "
  +"          '0'                                                                                                   "
  +"       END PERIOD,                                                                                              "
  +"       APPSCENE.BUSI_SCENE_ID UAPCONTEXTID,                                                                     "
  +"       (SELECT RE.UPLOAD_CONTEXTID                                                                              "
  +"          FROM UAP_BUSI_SCENE_ID_REALATION RE                                                                   "
  +"         WHERE RE.UAP_CONTEXTID = APPSCENE.BUSI_SCENE_ID AND RE.SCENE_TYPE='1') CONTEXTID,                                            "
  +"       SUM(DECODE(INFO.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0)) QQVALUE,                                       "
  +"       SUM(DECODE(INFO.CHECK_STATUS, '1', 1, 0)) YXVALUE,                                                       "
  +"       SUM(DECODE(INFO.CHECK_STATUS, '2', 1, 0)) JJVALUE,                                                       "
  +"       SUM(DECODE(INFO.CHECK_STATUS, '0', 1, 0)) CSVALUE                                                        "
  +"  FROM UAP_APP_SCENE      APPSCENE,                                                                             "
  +"       UAP_APP_SCENE_DATA APPR,                                                                                 "
  +"       UAP_GOLD_INFO      INFO                                                                                  "
  +" WHERE APPSCENE.BUSI_SCENE_ID = APPR.APP_SCENE_ID                                                               "
  +"   AND INFO.OPERATE_TYPE = '1'                                                                                  "
  +"   AND APPR.OPERATE_ID = INFO.OPERATE_ID                                                                          "
  ;
	
  public static final String A4_GOLD_OPERATE_APP_PART2_SQL =
   " GROUP BY APPSCENE.BUSI_SCENE_ID,                                                                               "
  +"          TO_CHAR((TRUNC(SYSDATE) +                                                                             "
  +"                  TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                      "
  +"                                          'yyyymmdd hh24:mi:ss'),                                               "
  +"                                  'yyyymmdd hh24:mi:ss') -                                                      "
  +"                         TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),                                       "
  +"                  'hh24:mi') || '-' ||                                                                          "
  +"          TO_CHAR((TRUNC(SYSDATE) +                                                                             "
  +"                  TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                      "
  +"                                          'yyyymmdd hh24:mi:ss'),                                               "
  +"                                  'yyyymmdd hh24:mi:ss') -                                                      "
  +"                         TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),                                   "
  +"                  'hh24:mi')                                                                                    "
  ;
  /**
   * zhang
   */
  public static final String A4_GOLD_OPERATE_APP_PART1_SQL_1 =
	   "SELECT 'APP' RESTYPE,																																														"
	  +"       CASE                                                                                                     "
	  +"        TO_CHAR((TRUNC(SYSDATE) +                                                                               "
	  +"                TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                        "
	  +"                                        'yyyymmdd hh24:mi:ss'),                                                 "
	  +"                                'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),       "
	  +"                'hh24:mi') || '-' ||                                                                            "
	  +"        TO_CHAR((TRUNC(SYSDATE) +                                                                               "
	  +"                TRUNC((TO_DATE(TO_CHAR(INFO.CREATE_TIME,                                                        "
	  +"                                        'yyyymmdd hh24:mi:ss'),                                                 "
	  +"                                'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 ) * 30 / 60 / 24),   "
	  +"                'hh24:mi')                                                                                      "
	  +"         WHEN '00:00-00:30' THEN                                                                                "
	  +"          '1'                                                                                                   "
	  +"         WHEN '00:30-01:00' THEN                                                                                "
	  +"          '2'                                                                                                   "
	  +"         WHEN '01:00-01:30' THEN                                                                                "
	  +"          '3'                                                                                                   "
	  +"         WHEN '01:30-02:00' THEN                                                                                "
	  +"          '4'                                                                                                   "
	  +"         WHEN '02:00-02:30' THEN                                                                                "
	  +"          '5'                                                                                                   "
	  +"         WHEN '02:30-03:00' THEN                                                                                "
	  +"          '6'                                                                                                   "
	  +"         WHEN '03:00-03:30' THEN                                                                                "
	  +"          '7'                                                                                                   "
	  +"         WHEN '03:30-04:00' THEN                                                                                "
	  +"          '8'                                                                                                   "
	  +"         WHEN '04:00-04:30' THEN                                                                                "
	  +"          '9'                                                                                                   "
	  +"         WHEN '04:30-05:00' THEN                                                                                "
	  +"          '10'                                                                                                  "
	  +"         WHEN '05:00-05:30' THEN                                                                                "
	  +"          '11'                                                                                                  "
	  +"         WHEN '05:30-06:00' THEN                                                                                "
	  +"          '12'                                                                                                  "
	  +"         WHEN '06:00-06:30' THEN                                                                                "
	  +"          '13'                                                                                                  "
	  +"         WHEN '06:30-07:00' THEN                                                                                "
	  +"          '14'                                                                                                  "
	  +"         WHEN '07:00-07:30' THEN                                                                                "
	  +"          '15'                                                                                                  "
	  +"         WHEN '07:30-08:00' THEN                                                                                "
	  +"          '16'                                                                                                  "
	  +"         WHEN '08:00-08:30' THEN                                                                                "
	  +"          '17'                                                                                                  "
	  +"         WHEN '08:30-09:00' THEN                                                                                "
	  +"          '18'                                                                                                  "
	  +"         WHEN '09:00-09:30' THEN                                                                                "
	  +"          '19'                                                                                                  "
	  +"         WHEN '09:30-10:00' THEN                                                                                "
	  +"          '20'                                                                                                  "
	  +"         WHEN '10:00-10:30' THEN                                                                                "
	  +"          '21'                                                                                                  "
	  +"         WHEN '10:30-11:00' THEN                                                                                "
	  +"          '22'                                                                                                  "
	  +"         WHEN '11:00-11:30' THEN                                                                                "
	  +"          '23'                                                                                                  "
	  +"         WHEN '11:30-12:00' THEN                                                                                "
	  +"          '24'                                                                                                  "
	  +"         WHEN '12:00-12:30' THEN                                                                                "
	  +"          '25'                                                                                                  "
	  +"         WHEN '12:30-13:00' THEN                                                                                "
	  +"          '26'                                                                                                  "
	  +"         WHEN '13:00-13:30' THEN                                                                                "
	  +"          '27'                                                                                                  "
	  +"         WHEN '13:30-14:00' THEN                                                                                "
	  +"          '28'                                                                                                  "
	  +"         WHEN '14:00-14:30' THEN                                                                                "
	  +"          '29'                                                                                                  "
	  +"         WHEN '14:30-15:00' THEN                                                                                "
	  +"          '30'                                                                                                  "
	  +"         WHEN '15:00-15:30' THEN                                                                                "
	  +"          '31'                                                                                                  "
	  +"         WHEN '15:30-16:00' THEN                                                                                "
	  +"          '32'                                                                                                  "
	  +"         WHEN '16:00-16:30' THEN                                                                                "
	  +"          '33'                                                                                                  "
	  +"         WHEN '16:30-17:00' THEN                                                                                "
	  +"          '34'                                                                                                  "
	  +"         WHEN '17:00-17:30' THEN                                                                                "
	  +"          '35'                                                                                                  "
	  +"         WHEN '17:30-18:00' THEN                                                                                "
	  +"          '36'                                                                                                  "
	  +"         WHEN '18:00-18:30' THEN                                                                                "
	  +"          '37'                                                                                                  "
	  +"         WHEN '18:30-19:00' THEN                                                                                "
	  +"          '38'                                                                                                  "
	  +"         WHEN '19:00-19:30' THEN                                                                                "
	  +"          '39'                                                                                                  "
	  +"         WHEN '19:30-20:00' THEN                                                                                "
	  +"          '40'                                                                                                  "
	  +"         WHEN '20:00-20:30' THEN                                                                                "
	  +"          '41'                                                                                                  "
	  +"         WHEN '20:30-21:00' THEN                                                                                "
	  +"          '42'                                                                                                  "
	  +"         WHEN '21:00-21:30' THEN                                                                                "
	  +"          '43'                                                                                                  "
	  +"         WHEN '21:30-22:00' THEN                                                                                "
	  +"          '44'                                                                                                  "
	  +"         WHEN '22:00-22:30' THEN                                                                                "
	  +"          '45'                                                                                                  "
	  +"         WHEN '22:30-23:00' THEN                                                                                "
	  +"          '46'                                                                                                  "
	  +"         WHEN '23:00-23:30' THEN                                                                                "
	  +"          '47'                                                                                                  "
	  +"         WHEN '23:30-00:00' THEN                                                                                "
	  +"          '48'                                                                                                  "
	  +"         ELSE                                                                                                   "
	  +"          '0'                                                                                                   "
	  +"       END PERIOD,                                                                                              "
	  +"       APPSCENE.BUSI_SCENE_ID UAPCONTEXTID,                                                                     "
	  +"       (SELECT RE.UPLOAD_CONTEXTID                                                                              "
	  +"          FROM UAP_BUSI_SCENE_ID_REALATION RE                                                                   "
	  +"         WHERE RE.UAP_CONTEXTID = APPSCENE.BUSI_SCENE_ID AND RE.SCENE_TYPE='1') CONTEXTID,                                            "
	  +"       SUM(DECODE(INFO.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0)) QQVALUE,                                       "
	  +"       SUM(DECODE(INFO.CHECK_STATUS, '1', 1, 0)) YXVALUE,                                                       "
	  +"       SUM(DECODE(INFO.CHECK_STATUS, '2', 1, 0)) JJVALUE,                                                       "
	  +"       (SUM(DECODE(INFO.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0))-SUM(DECODE(INFO.CHECK_STATUS, '1', 1, 0))-SUM(DECODE(INFO.CHECK_STATUS, '2', 1, 0))) CSVALUE,                                                   "
	  +" 	SUM(DECODE(INFO.CHECK_STATUS, '1', 1, 0)) CZVALUE "
	  +"  FROM UAP_APP_SCENE      APPSCENE,                                                                             "
	  +"       UAP_APP_SCENE_DATA APPR,                                                                                 "
	  +"       UAP_GOLD_INFO      INFO                                                                                  "
	  +" WHERE APPSCENE.BUSI_SCENE_ID = APPR.APP_SCENE_ID                                                               "
	  +"   AND INFO.OPERATE_TYPE = '1'                                                                                  "
	  +"   AND APPR.OPERATE_ID = INFO.OPERATE_ID                                                                          "
	  ;
  /**
   * ZHANG
   */
  public static final String A4_GOLD_OPERATE_SYS_PART1_SQL_2 =
	   "SELECT 'SYS' RESTYPE,CASE TO_CHAR((TRUNC(SYSDATE) +        																		    " 
	  +"                 TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,                                        " 
	  +"                                         'yyyymmdd hh24:mi:ss'),                                  " 
	  +"                 'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 -1) * 30 / 60 / 24),        " 
	  +"                 'hh24:mi') || '-' ||                                                             " 
	  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                " 
	  +"                 TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,                                        " 
	  +"                                         'yyyymmdd hh24:mi:ss'),                                  " 
	  +"              'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),       " 
	  +"                 'hh24:mi')                                                                       " 
	  +"                 WHEN '00:00-00:30' THEN '1'                                                      " 
	  +"                 WHEN '00:30-01:00' THEN '2'                                                      " 
	  +"                 WHEN '01:00-01:30' THEN '3'                                                      " 
	  +"                 WHEN '01:30-02:00' THEN '4'                                                      " 
	  +"                 WHEN '02:00-02:30' THEN '5'                                                      " 
	  +"                 WHEN '02:30-03:00' THEN '6'                                                      " 
	  +"                 WHEN '03:00-03:30' THEN '7'                                                      " 
	  +"                 WHEN '03:30-04:00' THEN '8'                                                      " 
	  +"                 WHEN '04:00-04:30' THEN '9'                                                      " 
	  +"                 WHEN '04:30-05:00' THEN '10'                                                     " 
	  +"                 WHEN '05:00-05:30' THEN '11'                                                     " 
	  +"                 WHEN '05:30-06:00' THEN '12'                                                     " 
	  +"                 WHEN '06:00-06:30' THEN '13'                                                     " 
	  +"                 WHEN '06:30-07:00' THEN '14'                                                     " 
	  +"                 WHEN '07:00-07:30' THEN '15'                                                     " 
	  +"                 WHEN '07:30-08:00' THEN '16'                                                     " 
	  +"                 WHEN '08:00-08:30' THEN '17'                                                     " 
	  +"                 WHEN '08:30-09:00' THEN '18'                                                     " 
	  +"                 WHEN '09:00-09:30' THEN '19'                                                     " 
	  +"                 WHEN '09:30-10:00' THEN '20'                                                     " 
	  +"                 WHEN '10:00-10:30' THEN '21'                                                     " 
	  +"                 WHEN '10:30-11:00' THEN '22'                                                     " 
	  +"                 WHEN '11:00-11:30' THEN '23'                                                     " 
	  +"                 WHEN '11:30-12:00' THEN '24'                                                     " 
	  +"                 WHEN '12:00-12:30' THEN '25'                                                     " 
	  +"                 WHEN '12:30-13:00' THEN '26'                                                     " 
	  +"                 WHEN '13:00-13:30' THEN '27'                                                     " 
	  +"                 WHEN '13:30-14:00' THEN '28'                                                     " 
	  +"                 WHEN '14:00-14:30' THEN '29'                                                     " 
	  +"                 WHEN '14:30-15:00' THEN '30'                                                     " 
	  +"                 WHEN '15:00-15:30' THEN '31'                                                     " 
	  +"                 WHEN '15:30-16:00' THEN '32'                                                     " 
	  +"                 WHEN '16:00-16:30' THEN '33'                                                     " 
	  +"                 WHEN '16:30-17:00' THEN '34'                                                     " 
	  +"                 WHEN '17:00-17:30' THEN '35'                                                     " 
	  +"                 WHEN '17:30-18:00' THEN '36'                                                     " 
	  +"                 WHEN '18:00-18:30' THEN '37'                                                     " 
	  +"                 WHEN '18:30-19:00' THEN '38'                                                     " 
	  +"                 WHEN '19:00-19:30' THEN '39'                                                     " 
	  +"                 WHEN '19:30-20:00' THEN '40'                                                     " 
	  +"                 WHEN '20:00-20:30' THEN '41'                                                     " 
	  +"                 WHEN '20:30-21:00' THEN '42'                                                     " 
	  +"                 WHEN '21:00-21:30' THEN '43'                                                     " 
	  +"                 WHEN '21:30-22:00' THEN '44'                                                     " 
	  +"                 WHEN '22:00-22:30' THEN '45'                                                     " 
	  +"                 WHEN '22:30-23:00' THEN '46'                                                     " 
	  +"                 WHEN '23:00-23:30' THEN '47'                                                     " 
	  +"                 WHEN '23:30-00:00' THEN '48'                                                     " 
	  +"                 ELSE '0' END                                                                     " 
	  +"                 PERIOD,                                                                          " 
	  +"         SYSSCENE.BUSI_SCENE_ID UAPCONTEXTID,                                                     " 
	  +"         (SELECT RE.UPLOAD_CONTEXTID FROM UAP_BUSI_SCENE_ID_REALATION RE                          " 
	  +"         WHERE RE.UAP_CONTEXTID = SYSSCENE.BUSI_SCENE_ID AND RE.SCENE_TYPE ='2') CONTEXTID,                              " 
	  +"         SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0)) QQVALUE,                " 
	  +"         SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, 0)) YXVALUE,                                      " 
	  +"         SUM(DECODE(INFOD.CHECK_STATUS, '2', 1, 0)) JJVALUE,                                      " 
	  +"         (SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0))-SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, 0))-SUM(DECODE(INFOD.CHECK_STATUS, '2', 1, 0))) CSVALUE,                                       " 
	 +"			 SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, 0)) CZVALUE "	
	  +"    FROM UAP_SYS_SCENE      SYSSCENE,                                                             " 
	  +"         UAP_SYS_SCENE_DATA SSD,                                                                  " 
	  +"         UAP_GOLD_INFO      INFOD                                                                 " 
	  +"   WHERE                                                                                          " 
	  +"   SYSSCENE.BUSI_SCENE_ID = SSD.SYS_SCENE_ID                                                      " 
	  +"   AND INFOD.OPERATE_TYPE IN ('2','3')                                                            " 
	  +"   AND INFOD.OPERATE_ID = SSD.META_DATA_ID                                                        " 
	  ;
  
  
  
  public static final String A4_GOLD_OPERATE_SYS_PART1_SQL =
   "SELECT 'SYS' RESTYPE,CASE TO_CHAR((TRUNC(SYSDATE) +        																		    " 
  +"                 TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,                                        " 
  +"                                         'yyyymmdd hh24:mi:ss'),                                  " 
  +"                 'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 -1) * 30 / 60 / 24),        " 
  +"                 'hh24:mi') || '-' ||                                                             " 
  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                " 
  +"                 TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,                                        " 
  +"                                         'yyyymmdd hh24:mi:ss'),                                  " 
  +"              'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),       " 
  +"                 'hh24:mi')                                                                       " 
  +"                 WHEN '00:00-00:30' THEN '1'                                                      " 
  +"                 WHEN '00:30-01:00' THEN '2'                                                      " 
  +"                 WHEN '01:00-01:30' THEN '3'                                                      " 
  +"                 WHEN '01:30-02:00' THEN '4'                                                      " 
  +"                 WHEN '02:00-02:30' THEN '5'                                                      " 
  +"                 WHEN '02:30-03:00' THEN '6'                                                      " 
  +"                 WHEN '03:00-03:30' THEN '7'                                                      " 
  +"                 WHEN '03:30-04:00' THEN '8'                                                      " 
  +"                 WHEN '04:00-04:30' THEN '9'                                                      " 
  +"                 WHEN '04:30-05:00' THEN '10'                                                     " 
  +"                 WHEN '05:00-05:30' THEN '11'                                                     " 
  +"                 WHEN '05:30-06:00' THEN '12'                                                     " 
  +"                 WHEN '06:00-06:30' THEN '13'                                                     " 
  +"                 WHEN '06:30-07:00' THEN '14'                                                     " 
  +"                 WHEN '07:00-07:30' THEN '15'                                                     " 
  +"                 WHEN '07:30-08:00' THEN '16'                                                     " 
  +"                 WHEN '08:00-08:30' THEN '17'                                                     " 
  +"                 WHEN '08:30-09:00' THEN '18'                                                     " 
  +"                 WHEN '09:00-09:30' THEN '19'                                                     " 
  +"                 WHEN '09:30-10:00' THEN '20'                                                     " 
  +"                 WHEN '10:00-10:30' THEN '21'                                                     " 
  +"                 WHEN '10:30-11:00' THEN '22'                                                     " 
  +"                 WHEN '11:00-11:30' THEN '23'                                                     " 
  +"                 WHEN '11:30-12:00' THEN '24'                                                     " 
  +"                 WHEN '12:00-12:30' THEN '25'                                                     " 
  +"                 WHEN '12:30-13:00' THEN '26'                                                     " 
  +"                 WHEN '13:00-13:30' THEN '27'                                                     " 
  +"                 WHEN '13:30-14:00' THEN '28'                                                     " 
  +"                 WHEN '14:00-14:30' THEN '29'                                                     " 
  +"                 WHEN '14:30-15:00' THEN '30'                                                     " 
  +"                 WHEN '15:00-15:30' THEN '31'                                                     " 
  +"                 WHEN '15:30-16:00' THEN '32'                                                     " 
  +"                 WHEN '16:00-16:30' THEN '33'                                                     " 
  +"                 WHEN '16:30-17:00' THEN '34'                                                     " 
  +"                 WHEN '17:00-17:30' THEN '35'                                                     " 
  +"                 WHEN '17:30-18:00' THEN '36'                                                     " 
  +"                 WHEN '18:00-18:30' THEN '37'                                                     " 
  +"                 WHEN '18:30-19:00' THEN '38'                                                     " 
  +"                 WHEN '19:00-19:30' THEN '39'                                                     " 
  +"                 WHEN '19:30-20:00' THEN '40'                                                     " 
  +"                 WHEN '20:00-20:30' THEN '41'                                                     " 
  +"                 WHEN '20:30-21:00' THEN '42'                                                     " 
  +"                 WHEN '21:00-21:30' THEN '43'                                                     " 
  +"                 WHEN '21:30-22:00' THEN '44'                                                     " 
  +"                 WHEN '22:00-22:30' THEN '45'                                                     " 
  +"                 WHEN '22:30-23:00' THEN '46'                                                     " 
  +"                 WHEN '23:00-23:30' THEN '47'                                                     " 
  +"                 WHEN '23:30-00:00' THEN '48'                                                     " 
  +"                 ELSE '0' END                                                                     " 
  +"                 PERIOD,                                                                          " 
  +"         SYSSCENE.BUSI_SCENE_ID UAPCONTEXTID,                                                     " 
  +"         (SELECT RE.UPLOAD_CONTEXTID FROM UAP_BUSI_SCENE_ID_REALATION RE                          " 
  +"         WHERE RE.UAP_CONTEXTID = SYSSCENE.BUSI_SCENE_ID AND RE.SCENE_TYPE ='2') CONTEXTID,                              " 
  +"         SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, '2', 1, '0', 1,'3',1, 0)) QQVALUE,                " 
  +"         SUM(DECODE(INFOD.CHECK_STATUS, '1', 1, 0)) YXVALUE,                                      " 
  +"         SUM(DECODE(INFOD.CHECK_STATUS, '2', 1, 0)) JJVALUE,                                      " 
  +"         SUM(DECODE(INFOD.CHECK_STATUS, '0', 1, 0)) CSVALUE                                       " 
  +"    FROM UAP_SYS_SCENE      SYSSCENE,                                                             " 
  +"         UAP_SYS_SCENE_DATA SSD,                                                                  " 
  +"         UAP_GOLD_INFO      INFOD                                                                 " 
  +"   WHERE                                                                                          " 
  +"   SYSSCENE.BUSI_SCENE_ID = SSD.SYS_SCENE_ID                                                      " 
  +"   AND INFOD.OPERATE_TYPE IN ('2','3')                                                            " 
  +"   AND INFOD.OPERATE_ID = SSD.META_DATA_ID                                                        " 
  ;
  
  public static final String A4_GOLD_OPERATE_SYS_PART2_SQL =
   "    GROUP BY SYSSCENE.BUSI_SCENE_ID,                                                              " 
  +"          TO_CHAR((TRUNC(SYSDATE) +                                                               " 
  +"                  TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,'yyyymmdd hh24:mi:ss'),                " 
  +"                  'yyyymmdd hh24:mi:ss')  - TRUNC(SYSDATE)) * 24 * 60 / 30- 1) * 30 / 60 / 24),   " 
  +"                  'hh24:mi') || '-' ||                                                            " 
  +"          TO_CHAR((TRUNC(SYSDATE) +                                                               " 
  +"                  TRUNC((TO_DATE(TO_CHAR(INFOD.CREATE_TIME,'yyyymmdd hh24:mi:ss'),                " 
  +"                  'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),   " 
  +"                  'hh24:mi')                                                                      " 
  ;
  
  public static final String A4_GOLD_OPERATE_APP_LOG_PART1_SQL =
	   "SELECT 'APP' RESTYPE,  				                                                                           "
	  +"        IAL.BANK_SCENE_ID,                                                                               "       
	  +"        CASE                                                                                             "       
	  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                       "       
	  +"                 TRUNC((TO_DATE(TO_CHAR(IAL.OPERATE_TIME,                                                "       
	  +"                                         'yyyymmdd hh24:mi:ss'),                                         "       
	  +"                 'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),               "
	  +"                 'hh24:mi') || '-' ||                                                                    "       
	  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                       "       
	  +"                 TRUNC((TO_DATE(TO_CHAR(IAL.OPERATE_TIME,                                                "       
	  +"                                         'yyyymmdd hh24:mi:ss'),                                         "       
	  +"              'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),              "
	  +"                 'hh24:mi')                                                                              "       
	  +"          WHEN '00:00-00:30' THEN                                                                        "       
	  +"           '1'                                                                                           "       
	  +"          WHEN '00:30-01:00' THEN                                                                        "       
	  +"           '2'                                                                                           "       
	  +"          WHEN '01:00-01:30' THEN                                                                        "       
	  +"           '3'                                                                                           "       
	  +"          WHEN '01:30-02:00' THEN                                                                        "       
	  +"           '4'                                                                                           "       
	  +"          WHEN '02:00-02:30' THEN                                                                        "       
	  +"           '5'                                                                                           "       
	  +"          WHEN '02:30-03:00' THEN                                                                        "       
	  +"           '6'                                                                                           "       
	  +"          WHEN '03:00-03:30' THEN                                                                        "       
	  +"           '7'                                                                                           "       
	  +"          WHEN '03:30-04:00' THEN                                                                        "       
	  +"           '8'                                                                                           "       
	  +"          WHEN '04:00-04:30' THEN                                                                        "       
	  +"           '9'                                                                                           "       
	  +"          WHEN '04:30-05:00' THEN                                                                        "       
	  +"           '10'                                                                                          "       
	  +"          WHEN '05:00-05:30' THEN                                                                        "       
	  +"           '11'                                                                                          "       
	  +"          WHEN '05:30-06:00' THEN                                                                        "       
	  +"           '12'                                                                                          "       
	  +"          WHEN '06:00-06:30' THEN                                                                        "       
	  +"           '13'                                                                                          "       
	  +"          WHEN '06:30-07:00' THEN                                                                        "       
	  +"           '14'                                                                                          "       
	  +"          WHEN '07:00-07:30' THEN                                                                        "       
	  +"           '15'                                                                                          "       
	  +"          WHEN '07:30-08:00' THEN                                                                        "       
	  +"           '16'                                                                                          "       
	  +"          WHEN '08:00-08:30' THEN                                                                        "       
	  +"           '17'                                                                                          "       
	  +"          WHEN '08:30-09:00' THEN                                                                        "       
	  +"           '18'                                                                                          "       
	  +"          WHEN '09:00-09:30' THEN                                                                        "       
	  +"           '19'                                                                                          "       
	  +"          WHEN '09:30-10:00' THEN                                                                        "       
	  +"           '20'                                                                                          "       
	  +"          WHEN '10:00-10:30' THEN                                                                        "       
	  +"           '21'                                                                                          "       
	  +"          WHEN '10:30-11:00' THEN                                                                        "       
	  +"           '22'                                                                                          "       
	  +"          WHEN '11:00-11:30' THEN                                                                        "       
	  +"           '23'                                                                                          "       
	  +"          WHEN '11:30-12:00' THEN                                                                        "       
	  +"           '24'                                                                                          "       
	  +"          WHEN '12:00-12:30' THEN                                                                        "       
	  +"           '25'                                                                                          "       
	  +"          WHEN '12:30-13:00' THEN                                                                        "       
	  +"           '26'                                                                                          "       
	  +"          WHEN '13:00-13:30' THEN                                                                        "       
	  +"           '27'                                                                                          "       
	  +"          WHEN '13:30-14:00' THEN                                                                        "       
	  +"           '28'                                                                                          "       
	  +"          WHEN '14:00-14:30' THEN                                                                        "       
	  +"           '29'                                                                                          "       
	  +"          WHEN '14:30-15:00' THEN                                                                        "       
	  +"           '30'                                                                                          "       
	  +"          WHEN '15:00-15:30' THEN                                                                        "       
	  +"           '31'                                                                                          "       
	  +"          WHEN '15:30-16:00' THEN                                                                        "       
	  +"           '32'                                                                                          "       
	  +"          WHEN '16:00-16:30' THEN                                                                        "       
	  +"           '33'                                                                                          "       
	  +"          WHEN '16:30-17:00' THEN                                                                        "       
	  +"           '34'                                                                                          "       
	  +"          WHEN '17:00-17:30' THEN                                                                        "       
	  +"           '35'                                                                                          "       
	  +"          WHEN '17:30-18:00' THEN                                                                        "       
	  +"           '36'                                                                                          "       
	  +"          WHEN '18:00-18:30' THEN                                                                        "       
	  +"           '37'                                                                                          "       
	  +"          WHEN '18:30-19:00' THEN                                                                        "       
	  +"           '38'                                                                                          "       
	  +"          WHEN '19:00-19:30' THEN                                                                        "       
	  +"           '39'                                                                                          "       
	  +"          WHEN '19:30-20:00' THEN                                                                        "       
	  +"           '40'                                                                                          "       
	  +"          WHEN '20:00-20:30' THEN                                                                        "       
	  +"           '41'                                                                                          "       
	  +"          WHEN '20:30-21:00' THEN                                                                        "       
	  +"           '42'                                                                                          "       
	  +"          WHEN '21:00-21:30' THEN                                                                        "       
	  +"           '43'                                                                                          "       
	  +"          WHEN '21:30-22:00' THEN                                                                        "       
	  +"           '44'                                                                                          "       
	  +"          WHEN '22:00-22:30' THEN                                                                        "       
	  +"           '45'                                                                                          "       
	  +"          WHEN '22:30-23:00' THEN                                                                        "       
	  +"           '46'                                                                                          "       
	  +"          WHEN '23:00-23:30' THEN                                                                        "       
	  +"           '47'                                                                                          "       
	  +"          WHEN '23:30-00:00' THEN                                                                        "       
	  +"           '48'                                                                                          "       
	  +"          ELSE                                                                                           "       
	  +"           '0'                                                                                           "       
	  +"        END PERIOD,                                                                                      "       
	  +"        COUNT(1) CZVALUE                                                                                 "       
	  +"   FROM IAP_APP_LOG IAL                                                                                  "       
	  +"  WHERE IAL.BANK_ISNEED = '1'                                                                            "       
	  +"    AND IAL.BANK_ISOPEN = '1'                                                                            "       
	  ;
  
  public static final String A4_GOLD_OPERATE_APP_LOG_PART2_SQL =   
	   "  GROUP BY IAL.BANK_SCENE_ID,                                                                            "       
	  +"           TO_CHAR((TRUNC(SYSDATE) +                                                                     "       
	  +"                   TRUNC((TO_DATE(TO_CHAR(IAL.OPERATE_TIME,                                              "       
	  +"                                           'yyyymmdd hh24:mi:ss'),                                       "       
	  +"                   'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30- 1) * 30 / 60 / 24),             "
	  +"                   'hh24:mi') || '-' ||                                                                  "       
	  +"           TO_CHAR((TRUNC(SYSDATE) +                                                                     "       
	  +"                   TRUNC((TO_DATE(TO_CHAR(IAL.OPERATE_TIME,                                              "       
	  +"                                           'yyyymmdd hh24:mi:ss'),                                       "       
	  +"                  'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),          "
	  +"                   'hh24:mi')                                                                            "  
      ;
  
  public static final String A4_GOLD_OPERATE_SYS_LOG_PART1_SQL =
	   "SELECT 'SYS' RESTYPE,           																																		"
	  +"        DSC.BANK_SCENE_ID,                                                                          "
	  +"        CASE                                                                                        "
	  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                  "
	  +"                 TRUNC((TO_DATE(TO_CHAR(DSC.OP_TIME, 'yyyymmdd hh24:mi:ss'),                        "
	  +"                    'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 -1) * 30 / 60 / 24),       "
	  +"                 'hh24:mi') || '-' ||                                                               "
	  +"         TO_CHAR((TRUNC(SYSDATE) +                                                                  "
	  +"                 TRUNC((TO_DATE(TO_CHAR(DSC.OP_TIME, 'yyyymmdd hh24:mi:ss'),                        "
	  +"                  'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),     "
	  +"                 'hh24:mi')                                                                         "
	  +"          WHEN '00:00-00:30' THEN                                                                   "
	  +"           '1'                                                                                      "
	  +"          WHEN '00:30-01:00' THEN                                                                   "
	  +"           '2'                                                                                      "
	  +"          WHEN '01:00-01:30' THEN                                                                   "
	  +"           '3'                                                                                      "
	  +"          WHEN '01:30-02:00' THEN                                                                   "
	  +"           '4'                                                                                      "
	  +"          WHEN '02:00-02:30' THEN                                                                   "
	  +"           '5'                                                                                      "
	  +"          WHEN '02:30-03:00' THEN                                                                   "
	  +"           '6'                                                                                      "
	  +"          WHEN '03:00-03:30' THEN                                                                   "
	  +"           '7'                                                                                      "
	  +"          WHEN '03:30-04:00' THEN                                                                   "
	  +"           '8'                                                                                      "
	  +"          WHEN '04:00-04:30' THEN                                                                   "
	  +"           '9'                                                                                      "
	  +"          WHEN '04:30-05:00' THEN                                                                   "
	  +"           '10'                                                                                     "
	  +"          WHEN '05:00-05:30' THEN                                                                   "
	  +"           '11'                                                                                     "
	  +"          WHEN '05:30-06:00' THEN                                                                   "
	  +"           '12'                                                                                     "
	  +"          WHEN '06:00-06:30' THEN                                                                   "
	  +"           '13'                                                                                     "
	  +"          WHEN '06:30-07:00' THEN                                                                   "
	  +"           '14'                                                                                     "
	  +"          WHEN '07:00-07:30' THEN                                                                   "
	  +"           '15'                                                                                     "
	  +"          WHEN '07:30-08:00' THEN                                                                   "
	  +"           '16'                                                                                     "
	  +"          WHEN '08:00-08:30' THEN                                                                   "
	  +"           '17'                                                                                     "
	  +"          WHEN '08:30-09:00' THEN                                                                   "
	  +"           '18'                                                                                     "
	  +"          WHEN '09:00-09:30' THEN                                                                   "
	  +"           '19'                                                                                     "
	  +"          WHEN '09:30-10:00' THEN                                                                   "
	  +"           '20'                                                                                     "
	  +"          WHEN '10:00-10:30' THEN                                                                   "
	  +"           '21'                                                                                     "
	  +"          WHEN '10:30-11:00' THEN                                                                   "
	  +"           '22'                                                                                     "
	  +"          WHEN '11:00-11:30' THEN                                                                   "
	  +"           '23'                                                                                     "
	  +"          WHEN '11:30-12:00' THEN                                                                   "
	  +"           '24'                                                                                     "
	  +"          WHEN '12:00-12:30' THEN                                                                   "
	  +"           '25'                                                                                     "
	  +"          WHEN '12:30-13:00' THEN                                                                   "
	  +"           '26'                                                                                     "
	  +"          WHEN '13:00-13:30' THEN                                                                   "
	  +"           '27'                                                                                     "
	  +"          WHEN '13:30-14:00' THEN                                                                   "
	  +"           '28'                                                                                     "
	  +"          WHEN '14:00-14:30' THEN                                                                   "
	  +"           '29'                                                                                     "
	  +"          WHEN '14:30-15:00' THEN                                                                   "
	  +"           '30'                                                                                     "
	  +"          WHEN '15:00-15:30' THEN                                                                   "
	  +"           '31'                                                                                     "
	  +"          WHEN '15:30-16:00' THEN                                                                   "
	  +"           '32'                                                                                     "
	  +"          WHEN '16:00-16:30' THEN                                                                   "
	  +"           '33'                                                                                     "
	  +"          WHEN '16:30-17:00' THEN                                                                   "
	  +"           '34'                                                                                     "
	  +"          WHEN '17:00-17:30' THEN                                                                   "
	  +"           '35'                                                                                     "
	  +"          WHEN '17:30-18:00' THEN                                                                   "
	  +"           '36'                                                                                     "
	  +"          WHEN '18:00-18:30' THEN                                                                   "
	  +"           '37'                                                                                     "
	  +"          WHEN '18:30-19:00' THEN                                                                   "
	  +"           '38'                                                                                     "
	  +"          WHEN '19:00-19:30' THEN                                                                   "
	  +"           '39'                                                                                     "
	  +"          WHEN '19:30-20:00' THEN                                                                   "
	  +"           '40'                                                                                     "
	  +"          WHEN '20:00-20:30' THEN                                                                   "
	  +"           '41'                                                                                     "
	  +"          WHEN '20:30-21:00' THEN                                                                   "
	  +"           '42'                                                                                     "
	  +"          WHEN '21:00-21:30' THEN                                                                   "
	  +"           '43'                                                                                     "
	  +"          WHEN '21:30-22:00' THEN                                                                   "
	  +"           '44'                                                                                     "
	  +"          WHEN '22:00-22:30' THEN                                                                   "
	  +"           '45'                                                                                     "
	  +"          WHEN '22:30-23:00' THEN                                                                   "
	  +"           '46'                                                                                     "
	  +"          WHEN '23:00-23:30' THEN                                                                   "
	  +"           '47'                                                                                     "
	  +"          WHEN '23:30-00:00' THEN                                                                   "
	  +"           '48'                                                                                     "
	  +"          ELSE                                                                                      "
	  +"           '0'                                                                                      "
	  +"        END PERIOD,                                                                                 "
	  +"        COUNT(1) CZVALUE                                                                            "
	  +"   FROM IAP_DEVICE_SESSION_CMD DSC                                                                  "
	  +"  WHERE DSC.BANK_TRIGGER_TYPE = '1'                                                                 "
	  ;	
  
  public static final String A4_GOLD_OPERATE_SYS_LOG_PART2_SQL = 
	   "  GROUP BY DSC.BANK_SCENE_ID,TO_CHAR((TRUNC(SYSDATE) +                                                                "
	  +"                   TRUNC((TO_DATE(TO_CHAR(DSC.OP_TIME,                                              "
	  +"                                           'yyyymmdd hh24:mi:ss'),                                  "
	  +"              'yyyymmdd hh24:mi:ss') - TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),             "
	  +"                   'hh24:mi') || '-' ||                                                             "
	  +"           TO_CHAR((TRUNC(SYSDATE) +                                                                "
	  +"                   TRUNC((TO_DATE(TO_CHAR(DSC.OP_TIME,                                              "
	  +"                                           'yyyymmdd hh24:mi:ss'),                                  "
	  +"               'yyyymmdd hh24:mi:ss') - trunc(sysdate)) * 24 * 60 / 30) * 30 / 60 / 24),        "
	  +"                   'hh24:mi')                                                                       "
   ;
  
  public static final String A4_GOLD_OPERATE_SYS_LOG_PART3_SQL =
	   " SELECT 'SYS' RESTYPE,                                                     "
	  +"      SC.BANK_SCENE_ID,                                                    "
	  +"      CASE TO_CHAR((TRUNC(SYSDATE) +                                       "
	  +"               TRUNC((TO_DATE(TO_CHAR(DS.LOGIN_TIME,                       "
	  +"                                       'yyyymmdd hh24:mi:ss'),             "
	  +"                               'yyyymmdd hh24:mi:ss') -                    "
	  +"                      TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24), "
	  +"               'hh24:mi') || '-' ||                                        "
	  +"       TO_CHAR((TRUNC(SYSDATE) +                                           "
	  +"               TRUNC((TO_DATE(TO_CHAR(DS.LOGIN_TIME,                       "
	  +"                                       'yyyymmdd hh24:mi:ss'),             "
	  +"                               'yyyymmdd hh24:mi:ss') -                    "
	  +"                      TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),     "
	  +"               'hh24:mi')                                                  "
	  +"        WHEN '00:00-00:30' THEN                                            "
	  +"         '1'                                                               "
	  +"        WHEN '00:30-01:00' THEN                                            "
	  +"         '2'                                                               "
	  +"        WHEN '01:00-01:30' THEN                                            "
	  +"         '3'                                                               "
	  +"        WHEN '01:30-02:00' THEN                                            "
	  +"         '4'                                                               "
	  +"        WHEN '02:00-02:30' THEN                                            "
	  +"         '5'                                                               "
	  +"        WHEN '02:30-03:00' THEN                                            "
	  +"         '6'                                                               "
	  +"        WHEN '03:00-03:30' THEN                                            "
	  +"         '7'                                                               "
	  +"        WHEN '03:30-04:00' THEN                                            "
	  +"         '8'                                                               "
	  +"        WHEN '04:00-04:30' THEN                                            "
	  +"         '9'                                                               "
	  +"        WHEN '04:30-05:00' THEN                                            "
	  +"         '10'                                                              "
	  +"        WHEN '05:00-05:30' THEN                                            "
	  +"         '11'                                                              "
	  +"        WHEN '05:30-06:00' THEN                                            "
	  +"         '12'                                                              "
	  +"        WHEN '06:00-06:30' THEN                                            "
	  +"         '13'                                                              "
	  +"        WHEN '06:30-07:00' THEN                                            "
	  +"         '14'                                                              "
	  +"        WHEN '07:00-07:30' THEN                                            "
	  +"         '15'                                                              "
	  +"        WHEN '07:30-08:00' THEN                                            "
	  +"         '16'                                                              "
	  +"        WHEN '08:00-08:30' THEN                                            "
	  +"         '17'                                                              "
	  +"        WHEN '08:30-09:00' THEN                                            "
	  +"         '18'                                                              "
	  +"        WHEN '09:00-09:30' THEN                                            "
	  +"         '19'                                                              "
	  +"        WHEN '09:30-10:00' THEN                                            "
	  +"         '20'                                                              "
	  +"        WHEN '10:00-10:30' THEN                                            "
	  +"         '21'                                                              "
	  +"        WHEN '10:30-11:00' THEN                                            "
	  +"         '22'                                                              "
	  +"        WHEN '11:00-11:30' THEN                                            "
	  +"         '23'                                                              "
	  +"        WHEN '11:30-12:00' THEN                                            "
	  +"         '24'                                                              "
	  +"        WHEN '12:00-12:30' THEN                                            "
	  +"         '25'                                                              "
	  +"        WHEN '12:30-13:00' THEN                                            "
	  +"         '26'                                                              "
	  +"        WHEN '13:00-13:30' THEN                                            "
	  +"         '27'                                                              "
	  +"        WHEN '13:30-14:00' THEN                                            "
	  +"         '28'                                                              "
	  +"        WHEN '14:00-14:30' THEN                                            "
	  +"         '29'                                                              "
	  +"        WHEN '14:30-15:00' THEN                                            "
	  +"         '30'                                                              "
	  +"        WHEN '15:00-15:30' THEN                                            "
	  +"         '31'                                                              "
	  +"        WHEN '15:30-16:00' THEN                                            "
	  +"         '32'                                                              "
	  +"        WHEN '16:00-16:30' THEN                                            "
	  +"         '33'                                                              "
	  +"        WHEN '16:30-17:00' THEN                                            "
	  +"         '34'                                                              "
	  +"        WHEN '17:00-17:30' THEN                                            "
	  +"         '35'                                                              "
	  +"        WHEN '17:30-18:00' THEN                                            "
	  +"         '36'                                                              "
	  +"        WHEN '18:00-18:30' THEN                                            "
	  +"         '37'                                                              "
	  +"        WHEN '18:30-19:00' THEN                                            "
	  +"         '38'                                                              "
	  +"        WHEN '19:00-19:30' THEN                                            "
	  +"         '39'                                                              "
	  +"        WHEN '19:30-20:00' THEN                                            "
	  +"         '40'                                                              "
	  +"        WHEN '20:00-20:30' THEN                                            "
	  +"         '41'                                                              "
	  +"        WHEN '20:30-21:00' THEN                                            "
	  +"         '42'                                                              "
	  +"        WHEN '21:00-21:30' THEN                                            "
	  +"         '43'                                                              "
	  +"        WHEN '21:30-22:00' THEN                                            "
	  +"         '44'                                                              "
	  +"        WHEN '22:00-22:30' THEN                                            "
	  +"         '45'                                                              "
	  +"        WHEN '22:30-23:00' THEN                                            "
	  +"         '46'                                                              "
	  +"        WHEN '23:00-23:30' THEN                                            "
	  +"         '47'                                                              "
	  +"        WHEN '23:30-00:00' THEN                                            "
	  +"         '48'                                                              "
	  +"        ELSE                                                               "
	  +"         '0'                                                               "
	  +"      END PERIOD,                                                          "
	  +"      COUNT(1) CZVALUE                                                     "
	  +" FROM IAP_DEVICE_SESSION DS, IAP_DEVICE_SESSION_CMD SC                     "
	  +"WHERE DS.SESSION_ID = SC.SESSION_ID                                        "
	  +"  AND DS.BANK_TRIGGER_TYPE = 0                                             "
	  ;
  
  public static final String A4_GOLD_OPERATE_SYS_LOG_PART4_SQL =
	   "GROUP BY SC.BANK_SCENE_ID,                                               "
	  +"      TO_CHAR((TRUNC(SYSDATE) +                                          "
	  +"              TRUNC((TO_DATE(TO_CHAR(DS.LOGIN_TIME,                      "
	  +"                                      'yyyymmdd hh24:mi:ss'),            "
	  +"                              'yyyymmdd hh24:mi:ss') -                   "
	  +"                     TRUNC(SYSDATE)) * 24 * 60 / 30 - 1) * 30 / 60 / 24),"
	  +"              'hh24:mi') || '-' ||                                       "
	  +"      TO_CHAR((TRUNC(SYSDATE) +                                          "
	  +"              TRUNC((TO_DATE(TO_CHAR(DS.LOGIN_TIME,                      "
	  +"                                      'yyyymmdd hh24:mi:ss'),            "
	  +"                              'yyyymmdd hh24:mi:ss') -                   "
	  +"                     TRUNC(SYSDATE)) * 24 * 60 / 30) * 30 / 60 / 24),    "
	  +"              'hh24:mi')                                                 "
	  ;
		
  public static final String UNION_ALL = " UNION ALL ";

}
