//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 10:12:49 上午 CST 
//


package com.ailk.check.xsd.smjka;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="province">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="100"/>
 *               &lt;enumeration value="200"/>
 *               &lt;enumeration value="210"/>
 *               &lt;enumeration value="220"/>
 *               &lt;enumeration value="230"/>
 *               &lt;enumeration value="240"/>
 *               &lt;enumeration value="250"/>
 *               &lt;enumeration value="270"/>
 *               &lt;enumeration value="280"/>
 *               &lt;enumeration value="290"/>
 *               &lt;enumeration value="311"/>
 *               &lt;enumeration value="351"/>
 *               &lt;enumeration value="371"/>
 *               &lt;enumeration value="431"/>
 *               &lt;enumeration value="451"/>
 *               &lt;enumeration value="471"/>
 *               &lt;enumeration value="531"/>
 *               &lt;enumeration value="551"/>
 *               &lt;enumeration value="571"/>
 *               &lt;enumeration value="591"/>
 *               &lt;enumeration value="731"/>
 *               &lt;enumeration value="771"/>
 *               &lt;enumeration value="791"/>
 *               &lt;enumeration value="851"/>
 *               &lt;enumeration value="871"/>
 *               &lt;enumeration value="891"/>
 *               &lt;enumeration value="898"/>
 *               &lt;enumeration value="931"/>
 *               &lt;enumeration value="951"/>
 *               &lt;enumeration value="971"/>
 *               &lt;enumeration value="991"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="createtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sum" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="begintime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="endtime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rcd" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="approvename">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="approvetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="requestid">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="approvemode">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="00"/>
 *                                   &lt;enumeration value="01"/>
 *                                   &lt;enumeration value="02"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="approveinfo">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{}NonZeroLenString">
 *                                   &lt;maxLength value="64"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "province",
    "createtime",
    "sum",
    "begintime",
    "endtime",
    "data"
})
@XmlRootElement(name = "smp")
public class Smp {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger province;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createtime;
    @XmlElement(required = true)
    protected BigInteger sum;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar begintime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endtime;
    @XmlElement(required = true)
    protected Smp.Data data;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProvince(BigInteger value) {
        this.province = value;
    }

    /**
     * Gets the value of the createtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatetime() {
        return createtime;
    }

    /**
     * Sets the value of the createtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatetime(XMLGregorianCalendar value) {
        this.createtime = value;
    }

    /**
     * Gets the value of the sum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSum() {
        return sum;
    }

    /**
     * Sets the value of the sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSum(BigInteger value) {
        this.sum = value;
    }

    /**
     * Gets the value of the begintime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBegintime() {
        return begintime;
    }

    /**
     * Sets the value of the begintime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBegintime(XMLGregorianCalendar value) {
        this.begintime = value;
    }

    /**
     * Gets the value of the endtime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndtime() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndtime(XMLGregorianCalendar value) {
        this.endtime = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Smp.Data }
     *     
     */
    public Smp.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Smp.Data }
     *     
     */
    public void setData(Smp.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rcd" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="approvename">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="approvetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="requestid">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="approvemode">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="00"/>
     *                         &lt;enumeration value="01"/>
     *                         &lt;enumeration value="02"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="approveinfo">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{}NonZeroLenString">
     *                         &lt;maxLength value="64"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rcd"
    })
    public static class Data {

        protected List<Smp.Data.Rcd> rcd;

        /**
         * Gets the value of the rcd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rcd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRcd().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Smp.Data.Rcd }
         * 
         * 
         */
        public List<Smp.Data.Rcd> getRcd() {
            if (rcd == null) {
                rcd = new ArrayList<Smp.Data.Rcd>();
            }
            return this.rcd;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="seq" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="approvename">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="approvetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="requestid">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="approvemode">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="00"/>
         *               &lt;enumeration value="01"/>
         *               &lt;enumeration value="02"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="approveinfo">
         *           &lt;simpleType>
         *             &lt;restriction base="{}NonZeroLenString">
         *               &lt;maxLength value="64"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "seq",
            "approvename",
            "approvetime",
            "requestid",
            "approvemode",
            "result",
            "approveinfo"
        })
        public static class Rcd {

            @XmlElement(required = true)
            protected BigInteger seq;
            @XmlElement(required = true)
            protected String approvename;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar approvetime;
            @XmlElement(required = true)
            protected String requestid;
            @XmlElement(required = true)
            protected String approvemode;
            @XmlElement(required = true)
            protected BigInteger result;
            @XmlElement(required = true)
            protected String approveinfo;

            /**
             * Gets the value of the seq property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSeq() {
                return seq;
            }

            /**
             * Sets the value of the seq property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSeq(BigInteger value) {
                this.seq = value;
            }

            /**
             * Gets the value of the approvename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApprovename() {
                return approvename;
            }

            /**
             * Sets the value of the approvename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApprovename(String value) {
                this.approvename = value;
            }

            /**
             * Gets the value of the approvetime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getApprovetime() {
                return approvetime;
            }

            /**
             * Sets the value of the approvetime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setApprovetime(XMLGregorianCalendar value) {
                this.approvetime = value;
            }

            /**
             * Gets the value of the requestid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestid() {
                return requestid;
            }

            /**
             * Sets the value of the requestid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestid(String value) {
                this.requestid = value;
            }

            /**
             * Gets the value of the approvemode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApprovemode() {
                return approvemode;
            }

            /**
             * Sets the value of the approvemode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApprovemode(String value) {
                this.approvemode = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setResult(BigInteger value) {
                this.result = value;
            }

            /**
             * Gets the value of the approveinfo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApproveinfo() {
                return approveinfo;
            }

            /**
             * Sets the value of the approveinfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApproveinfo(String value) {
                this.approveinfo = value;
            }

        }

    }

}
